### ISSUE TITLE
about test.py

### ISSUE THREAD

**Issue by Athirasatheeshkumar** [gurkirt/2D-kinectics#1]
I downloaded the pretrained models and i would like to implement it.can you guide me through how to use the pretrained models in test.py?

**Comment by gurkirt** [comment]
try to run test.py and see if you get any error then solve them one by one.

**Comment by Shanmugavadivelugopal** [comment]
i got this error,
Traceback (most recent call last):
  File "test.py", line 331, in <module>
    main()
  File "test.py", line 135, in main
    args.root += args.dataset + '/'
AttributeError: 'Namespace' object has no attribute 'root'
i am running in colab.Can you give me any suggestions regarding this.

**Comment by gurkirt** [comment]
change the hostname on line 114 to your machine's name
